-- Run this SQL in your Supabase SQL Editor to create the tables.
-- It will store student enrollment data, payment tokens, shipping parcel addresses, and settings.

-- 1. registrations table
CREATE TABLE IF NOT EXISTS registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  mobile TEXT NOT NULL,
  delivery_type TEXT NOT NULL, -- 'pickup' or 'delivery'
  address TEXT,
  city TEXT,
  state TEXT,
  pincode TEXT,
  amount_paid NUMERIC NOT NULL,
  razorpay_order_id TEXT UNIQUE,
  razorpay_payment_id TEXT UNIQUE,
  payment_status TEXT DEFAULT 'pending', -- 'pending', 'paid', 'failed'
  graphy_status TEXT DEFAULT 'pending', -- 'pending', 'success', 'failed'
  shipping_status TEXT DEFAULT 'not_applicable', -- 'not_applicable', 'pending_shipment', 'shipped'
  tracking_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. settings table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Seed initial admin and viewer passwords
INSERT INTO settings (key, value) VALUES 
('admin_password', 'Gauranga@!08smvd'),
('viewer_password', 'Prabhupada@108')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
-- Enable RLS (Row Level Security)
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Policies for "registrations" table
-- 1. Allow public checkout inserts (anonymous students checkout before being logged in)
CREATE POLICY "Allow anonymous checkout inserts" 
  ON registrations FOR INSERT 
  TO anon, service_role 
  WITH CHECK (true);

-- 2. Allow SELECT and UPDATE operations for backend API queries using publishable/service keys
CREATE POLICY "Allow select registrations for backend" 
  ON registrations FOR SELECT 
  TO anon, service_role 
  USING (true);

CREATE POLICY "Allow update registrations for backend" 
  ON registrations FOR UPDATE 
  TO anon, service_role 
  USING (true)
  WITH CHECK (true);

-- Policies for "settings" table
-- 1. Allow SELECT queries for password checks
CREATE POLICY "Allow select settings for auth check" 
  ON settings FOR SELECT 
  TO anon, service_role 
  USING (true);

-- 2. Allow UPDATE queries for password settings changes
CREATE POLICY "Allow update settings for password change" 
  ON settings FOR UPDATE 
  TO anon, service_role 
  USING (true)
  WITH CHECK (true);


